---
title: "R Bioinformatics Cookbook, Exercises"
author: "Kristian Bragge"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Environment setup, set eval=true to run
```{r, eval=FALSE}
install.packages("cowplot")
install.packages("dplyr")
install.packages("ggdist")
install.packages("ggeasy")
install.packages("ggforce")
install.packages("gghighlight")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("ggridges")
install.packages("palmerpenguins")
install.packages("patchwork")
install.packages("plotly")
```


# Exercises
## Chapter 3.
### Recipe 1.
```{r chp2pack}
library(ggplot2)
library(palmerpenguins)

#base
p <- ggplot(data = penguins) + 
  aes(x = bill_length_mm, y = bill_depth_mm)
#geoms
p + geom_point() +
  geom_smooth(method = "lm") + 
  geom_boxplot()
#order
p + geom_boxplot() + 
  geom_point() + 
  geom_smooth(method="lm")

#iterate
penguins |>
  dplyr::filter(!is.na(sex)) |>
  ggplot() + 
  aes(x=species, y=bill_length_mm) + 
  geom_boxplot(position = position_dodge(width = 0.75)) +
  geom_dotplot( binaxis = 'y',
                stackdir = 'center',
                method = "histodot",
                position = position_dodge(width = 0.75),
                alpha = 0.5,
                dotsize= 0.5)
#there's more
penguins |>
  dplyr::filter(!is.na(sex)) |>
  ggplot() + 
  aes(x = bill_depth_mm, y = bill_length_mm, size = island) + 
  geom_jitter(aes(colour = species)) + 
  geom_point(aes(shape=sex), alpha = 0.5) +
  scale_colour_brewer(palette = "Set2")
```
### Recipe 2.
```{r}
library(ggplot2)
library(ggridges)
library(palmerpenguins)

ggplot(data = penguins) + 
  aes(x=bill_length_mm, y=species, fill = species, color = species) +
  geom_density_ridges(scale = 2, position = "raincloud", alpha = 0.5, jittered_points = TRUE) + 
  theme_ridges()

ggplot(data = penguins) + 
  aes(x=bill_length_mm, y=species, fill = stat(x)) + 
        geom_density_ridges_gradient(scale = 2, rel_min_height = 0.01) +
        theme_ridges()

ggplot(data = penguins) + 
  aes(x = bill_length_mm, y = species,
      fill = factor(stat(quantile))) + 
  stat_density_ridges(
    geom = "density_ridges_gradient",
    calc_ecdf = TRUE,
    quantiles = c(0.05, 0.95)) +
  scale_fill_manual(
    name = "Probability", values = alpha(c("goldenrod","gray","steelblue"),0.5),
    labels = c("< 0,05", "0.05 - 0.095", "> 0,95")) +
  theme_ridges()
```



### Recipe 3.
```{r}
library(ggplot2)
library(ggeasy)
library(palmerpenguins)

p <- penguins |>
  dplyr::filter(!is.na(sex)) |>
  ggplot() + 
  aes(x = species, y = bill_length_mm) + 
  geom_boxplot(aes(fill=sex),
               position = position_dodge(width = 0.75)) +
  geom_dotplot(
    aes(fill=sex),
    binaxis = 'y',
    stackdir= 'center',
    method = 'histodot',
    position = position_dodge(width = 0.75),
    alpha = 0.5,
    dotsize = 0.5)+
  theme_minimal()
#customizations
p + easy_legend_at("bottom") + 
  easy_labs(title = "Examples title", subtitle = "by species and sex",
            x = "species",y="length") + 
  easy_remove_x_axis("title") +
  easy_x_axis_labels_size(18)+
 # easy_x_axis_labels_size(18)+
  easy_y_axis_labels_size(18)+
  easy_y_axis_title_size(18)+
  easy_remove_legend_title()+
  easy_plot_legend_size(14)


```

### Recipe 4.
```{r}
library(rbioinfcookbook)
library(ggplot2)
library(gghighlight)

fission_ge |>
  dplyr::mutate(signif = dplyr::if_else(padj < 0.05, TRUE, FALSE), 
                scaled_p = -log10(padj)) |>
  ggplot() + 
  aes(x=log2FoldChange, y=scaled_p) + 
  geom_point(aes(colour = signif)) + 
  gghighlight(scaled_p >10, label_key = id)

ggplot(ath_ts) + 
         aes(x=time, y=logFC) +
         geom_line(aes(colour=target_id)) + 
         scale_x_continuous(breaks = c(0,3,6,12), labels = c("0h","3h","6h","12h"))+
         gghighlight(
           min(P.Value) < 0.05,
             unhighlighted_params = 
               list(
                 linewidth=0.5,
                 colour=alpha("gray",0.2)))
```

### Recipe 5.
```{r}
library(ggplot2)
library(ggdist)
library(palmerpenguins)

ggplot(penguins) +
  aes(x = flipper_length_mm, y=island) +
  geom_dots(side="bottomleft",aes(colour=island)) +
  stat_slabinterval(aes(fill=island)) +
  theme_minimal()

ggplot(penguins) + 
  aes(x=flipper_length_mm, y=island) +
  stat_halfeye(aes(fill=stat((x>190&x<200))))+
  geom_vline(xintercept=c(190,200),linetype="dashed")+
  scale_fill_manual(values=c("gray","steelblue"))+
  theme_minimal()

ggplot(penguins) + 
  aes(x=flipper_length_mm, y=island) +
  stat_gradientinterval(aes(colour=island, fill=island))+
  theme_minimal()
```


### Recipe 6.
```{r}
library(ggplot2)
library(plotly)
library(rbioinfcookbook)

p <- ggplot(allele_freqs) +
  aes(x=Pos, y=Allele_Freq, label = info) +
  geom_point(aes(colour = type)) +
  facet_grid(Chr ~., scales= "free_x", space="free") +
  scale_colour_manual(values = c("steelblue", "gray", "goldenrod", "red")) +
  theme_minimal()

ggplotly(p, dynamicTicks = TRUE,
         dragmode = "zoom",
         tooltip = c("Chr", "Pos", "info"))

```



### Recipe 7.
```{r}
library(rbioinfcookbook)
library(ggplot2)
library(ggrepel)
set.seed(44)

fission_ge |> dplyr::mutate(
  signif = dplyr::if_else(padj < 0.05,TRUE,FALSE),
  scaled_p=-log10(padj)
) |>
  ggplot() + 
  geom_text_repel(aes(x=log2FoldChange, y=scaled_p, label=id),
                  max.time=60,
                  point.padding=NA,
                  arrow = arrow(
                    length = unit(0.03, "npc"),
                    type="closed",
                    ends="last",
                    angle = 15
                    ),
                  force=10,
                  xlim=c(NA,NA)) + 
  geom_point(aes(x=log2FoldChange, y=scaled_p,colour=signif)) + 
  theme_minimal()

```

### Recipe 8.
```{r}
library(rbioinfcookbook)
library(ggplot2)
library(ggforce)

allele_freqs |>
  dplyr::filter(Chr == 1) |>
  ggplot() +
  aes(x=Pos, y=Allele_Freq, label=info) + 
  geom_point(aes(colour=type)) + 
  facet_grid(Chr ~.,scales="free_x",space="free") + 
  scale_colour_manual(values=c("steelblue","gray","goldenrod","red")) +
  facet_zoom(xlim=c(1000000,2000000))

library(palmerpenguins)
penguins |>
  ggplot() + 
  aes(x=bill_depth_mm, y=bill_length_mm, colour=island) +
  geom_point() +
  facet_zoom(x= island=="Dream", zoom.data = island=="Dream")
```

### Recipe 9.
```{r}
library(rbioinfcookbook)
library(palmerpenguins)
library(ggplot2)
library(ggridges)
library(gghighlight)
library(ggdist)

p1 <- ggplot(data=penguins) + 
               aes(x=bill_length_mm, y=species,
                   fill = factor(stat(quantile))) +
               stat_density_ridges(geom = "density_ridges_gradient",
                                   calc_ecdf=TRUE,
                                   quantiles = c(0.05, 0.95))+
               scale_fill_manual(
                 name="Probability",
                 values=alpha(c("goldenrod",
                                "gray","steelblue"),0.5),
                 labels = c("<0.05","0.05 to 0.95",">0.95"),
                 guide=guide_legend(nrow=3,byrow=TRUE)
               ) +
  theme_ridges() +
  theme(legend.position = "bottom")

p2 <- fission_ge |>
  dplyr::mutate(
    signif = dplyr::if_else(padj<0.05,TRUE,FALSE),
    scaled_p=-log10(padj)
  ) |>
  ggplot()+
aes(x=log2FoldChange,y=scaled_p)+
  geom_point(aes(colour=signif))+
  gghighlight(scaled_p>10, label_key=id)+
  theme(legend.position="bottom")

p3 <- ggplot(penguins)+
  aes(x=flipper_length_mm,y=island,)+
  stat_halfeye(aes(fill=stat((x>190&x<200)))) +
  geom_vline(xintercept = c(190,200), linetype="dashed")+
  scale_fill_manual(values=c("gray","steelblue"),
                    guide=guide_legend(nrow=2,byrow=TRUE))+
  theme_minimal() +
  theme(legend.position="bottom")

p4 <- allele_freqs |>
  dplyr::filter(Chr==1) |>
  ggplot() +
  aes(x=Pos,y=Allele_Freq,label=info) +
  geom_point(aes(colour=type)) +
  facet_grid(Chr ~., scales="free_x",space="free")+
  scale_colour_manual(
    values=c("steelblue","gray","goldenrod","red"),
    labels=c("CDS","NON-CDS","NON-SYN-Coding","CTGA"))+
  theme(legend.position="bottom")

library(cowplot)
left_column <- plot_grid(p1+theme(legend.position = "none"),
                         p2+theme(legend.position = "none"),
                         p3+theme(legend.position = "none"),
                         ncol=1,labels=c("A","B","C"))

l1 <- get_legend(p1) #doesnt return legend like in book, returns first component
l3 <- get_legend(p3)

right_column <- plot_grid(l1,NULL,l3,ncol=1)

two_cols <- plot_grid(left_column, right_column, ncol=2,rel_widths=c(0.66,0.34))
labelled_4 <- plot_grid(p4, labels="D")

plot_grid(two_cols,labelled_4,ncol=1, rel_heights=c(0.6,0.4))
  


```